#!/usr/bin/env python3
"""
Task Completion Reporter
Generates completion reports for Claude Code tasks
"""

from datetime import datetime
from typing import Dict, List


def generate_completion_report(
    task_name: str,
    description: str = "",
    actions_taken: List[str] = None,
    results: Dict = None
) -> str:
    """
    Generate a structured completion report for a task

    Args:
        task_name: Name of the completed task
        description: Task description
        actions_taken: List of actions performed
        results: Dictionary of results/outcomes

    Returns:
        Formatted completion report string
    """
    report_lines = [
        f"# Task Completion Report",
        f"",
        f"**Task:** {task_name}",
        f"**Completed:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"",
    ]

    if description:
        report_lines.extend([
            f"## Description",
            f"{description}",
            f"",
        ])

    if actions_taken:
        report_lines.extend([
            f"## Actions Taken",
            "",
        ])
        for action in actions_taken:
            report_lines.append(f"- {action}")
        report_lines.append("")

    if results:
        report_lines.extend([
            f"## Results",
            "",
        ])
        for key, value in results.items():
            report_lines.append(f"- **{key}:** {value}")
        report_lines.append("")

    report_lines.append(f"---")
    report_lines.append(f"*Generated by Claude Code Task Manager*")

    return "\n".join(report_lines)


def generate_batch_completion_report(completed_tasks: List[Dict]) -> str:
    """
    Generate a report for multiple completed tasks

    Args:
        completed_tasks: List of task dictionaries with completion info

    Returns:
        Formatted batch completion report
    """
    report_lines = [
        f"# Batch Task Completion Report",
        f"",
        f"**Completed:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"**Tasks Completed:** {len(completed_tasks)}",
        f"",
        f"## Completed Tasks",
        f"",
    ]

    for i, task in enumerate(completed_tasks, 1):
        task_name = task.get("task_name", "Unknown Task")
        active_form = task.get("active_form", "")

        report_lines.append(f"{i}. **{task_name}**")
        if active_form:
            report_lines.append(f"   - Action: {active_form}")

        if task.get("description"):
            report_lines.append(f"   - {task['description']}")

        if task.get("results"):
            for key, value in task["results"].items():
                report_lines.append(f"   - {key}: {value}")

        report_lines.append("")

    report_lines.append(f"---")
    report_lines.append(f"*Generated by Claude Code Task Manager*")

    return "\n".join(report_lines)


def create_completion_summary(
    task_name: str,
    outcome: str = "Successfully completed",
    details: str = None
) -> str:
    """
    Create a brief completion summary (one-liner or short paragraph)

    Args:
        task_name: Name of the completed task
        outcome: Brief outcome description
        details: Optional additional details

    Returns:
        Brief completion summary
    """
    summary = f"✓ {task_name}: {outcome}"

    if details:
        summary += f"\n  {details}"

    return summary


if __name__ == "__main__":
    # Test report generation
    report = generate_completion_report(
        task_name="Implement Git-based task storage",
        description="Convert task manager from SQLite to Git-based file storage",
        actions_taken=[
            "Created git_storage.py with GitTaskStorage class",
            "Implemented task CRUD operations with Git commits",
            "Added automatic Git sync on task read/write",
            "Created completion reporting system"
        ],
        results={
            "Files Created": "git_storage.py, completion_reporter.py",
            "Git Integration": "Automatic commit and push",
            "Storage Format": "JSON files in ~/claude-tasks"
        }
    )

    print(report)
    print("\n" + "="*60 + "\n")

    # Test batch report
    batch_report = generate_batch_completion_report([
        {
            "task_name": "Convert to Git storage",
            "active_form": "Converting to Git-based storage",
            "description": "Replaced SQLite with Git-backed JSON files"
        },
        {
            "task_name": "Update hooks",
            "active_form": "Updating hooks for Git integration",
            "description": "Modified post_tool_use hook to use Git storage"
        }
    ])

    print(batch_report)
